# Created with package metadata maintained in the Humungousaur repository.
PackageIdentifier: BhaveshPabnani.Humungousaur
PackageVersion: 0.1.4
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
