from __future__ import annotations

from humungousaur.tools.base import Tool

from .common import extract_urls
from .live_tools import (
    BrowserLiveClickCoordinatesTool,
    BrowserLiveClickTool,
    BrowserLiveCloseTabTool,
    BrowserLiveCloseTool,
    BrowserLiveDownloadTool,
    BrowserLiveDropdownOptionsTool,
    BrowserLiveEvaluateJsTool,
    BrowserLiveNewTabTool,
    BrowserLiveObserveTool,
    BrowserLiveOpenTool,
    BrowserLivePressKeyTool,
    BrowserLiveQuerySelectorTool,
    BrowserLiveSavePdfTool,
    BrowserLiveScreenshotTool,
    BrowserLiveScrollToTextTool,
    BrowserLiveScrollTool,
    BrowserLiveSearchTool,
    BrowserLiveSelectOptionTool,
    BrowserLiveStatusTool,
    BrowserLiveSwitchTabTool,
    BrowserLiveTabsTool,
    BrowserLiveTypeTool,
    BrowserLiveUploadFileTool,
    BrowserLiveWaitTool,
)
from .static_tools import (
    BrowserBackTool,
    BrowserClickElementTool,
    BrowserClickLinkTool,
    BrowserExtractTool,
    BrowserFillFormTool,
    BrowserFindTextTool,
    BrowserForgetSessionTool,
    BrowserObserveTool,
    BrowserOpenTool,
    BrowserSessionsTool,
    BrowserSubmitFormTool,
    BrowserTypeTool,
    FetchWebPageTool,
    ResearchWebPagesTool,
)

def default_browser_tools() -> dict[str, Tool]:
    tools: list[Tool] = [
        FetchWebPageTool(),
        ResearchWebPagesTool(),
        BrowserSessionsTool(),
        BrowserObserveTool(),
        BrowserExtractTool(),
        BrowserOpenTool(),
        BrowserClickLinkTool(),
        BrowserClickElementTool(),
        BrowserBackTool(),
        BrowserTypeTool(),
        BrowserFindTextTool(),
        BrowserLiveStatusTool(),
        BrowserLiveOpenTool(),
        BrowserLiveObserveTool(),
        BrowserLiveClickTool(),
        BrowserLiveTypeTool(),
        BrowserLiveScrollTool(),
        BrowserLiveScrollToTextTool(),
        BrowserLiveWaitTool(),
        BrowserLiveTabsTool(),
        BrowserLiveSearchTool(),
        BrowserLiveNewTabTool(),
        BrowserLiveSwitchTabTool(),
        BrowserLiveCloseTabTool(),
        BrowserLiveQuerySelectorTool(),
        BrowserLiveDropdownOptionsTool(),
        BrowserLiveSelectOptionTool(),
        BrowserLivePressKeyTool(),
        BrowserLiveClickCoordinatesTool(),
        BrowserLiveUploadFileTool(),
        BrowserLiveDownloadTool(),
        BrowserLiveSavePdfTool(),
        BrowserLiveEvaluateJsTool(),
        BrowserLiveScreenshotTool(),
        BrowserLiveCloseTool(),
        BrowserFillFormTool(),
        BrowserSubmitFormTool(),
        BrowserForgetSessionTool(),
    ]
    return {tool.name: tool for tool in tools}
